import dynamic from 'next/dynamic';

export const TemplateEditors: Record<string, any> = {
  home: dynamic(() => import('./HomeEditor')),
  homepage: dynamic(() => import('./HomeEditor')),
  'home-page': dynamic(() => import('./HomeEditor')),
  about: dynamic(() => import('./NewAboutEditor')),
  'about-page': dynamic(() => import('./NewAboutEditor')),
  'new-about': dynamic(() => import('./NewAboutEditor')),
  newabout: dynamic(() => import('./NewAboutEditor')),
  services: dynamic(() => import('./ServicesEditor')),
  'service-detail': dynamic(() => import('./ServiceDetailEditor')),
  servicedetail: dynamic(() => import('./ServiceDetailEditor')),
  team: dynamic(() => import('./TeamEditor')),
  careers: dynamic(() => import('./CareersEditor')),
  gallery: dynamic(() => import('./GalleryEditor')),
  faq: dynamic(() => import('./FAQEditor')),
  contact: dynamic(() => import('./ContactEditor')),
  reviews: dynamic(() => import('./ReviewsEditor')),
  blog: dynamic(() => import('./BlogEditor')),
  settings: dynamic(() => import('./SettingsEditor')),
  'service-area': dynamic(() => import('./LocationEditor')),
  location: dynamic(() => import('./LocationEditor')),
  locations: dynamic(() => import('./LocationEditor')),
  country: dynamic(() => import('./CountryEditor')),
  state: dynamic(() => import('./StateEditor')),
  industry: dynamic(() => import('./IndustryEditor')),
  industries: dynamic(() => import('./IndustryEditor')),
};
